name: Build iOS App

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias
        run: |
          set -e
          npm ci
          npm run generate

      - name: Agregar sync iOS
        run: |
          set -e
          npx cap sync ios

      - name: Configurar certificados y firma
        env:
          APPLE_CERTIFICATE_BASE64: ${{ secrets.DEV_APPLE_CERTIFICATE_BASE64 }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_PROVISIONING_PROFILE_BASE64: ${{ secrets.DEV_APPLE_PROVISIONING_PROFILE_BASE64 }}
        run: |
          set -e
          CERT_PATH=$RUNNER_TEMP/apple_certificate.p12
          PROFILE_PATH=$RUNNER_TEMP/profile.mobileprovision

          echo "$APPLE_CERTIFICATE_BASE64" | base64 --decode -o $CERT_PATH
          echo "$APPLE_PROVISIONING_PROFILE_BASE64" | base64 --decode -o $PROFILE_PATH

          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import $CERT_PATH -P "$APPLE_CERTIFICATE_PASSWORD" -A
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
          security list-keychains -d user -s build.keychain
          security set-keychain-settings -lut 21600
          security find-identity -v

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PROFILE_PATH ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Verificar perfil de aprovisionamiento
        run: |
          set -e
          ls -l ~/Library/MobileDevice/Provisioning\ Profiles/
          security find-identity -v -p codesigning

      - name: Instalar CocoaPods
        run: |
          set -e
          cd ios/App
          pod install

      - name: Reemplazar variables en exportOptions.plist
        env:
          APPLE_BUNDLE_ID: ${{ secrets.APPLE_BUNDLE_ID }}
          PROVISIONING_PROFILE_NAME: ${{ secrets.DEV_PROVISIONING_PROFILE_NAME }}
          METHOD: development
        run: |
          set -e
          sed -i.bak 's|${APPLE_BUNDLE_ID}|'"${APPLE_BUNDLE_ID}"'|g' ios/App/exportOptions.plist
          sed -i.bak 's|${PROVISIONING_PROFILE_NAME}|'"${PROVISIONING_PROFILE_NAME}"'|g' ios/App/exportOptions.plist
          sed -i.bak 's|${METHOD}|'"${METHOD}"'|g' ios/App/exportOptions.plist
          rm ios/App/exportOptions.plist.bak

          # Verificar si se reemplazó correctamente
          cat ios/App/exportOptions.plist

      # - name: Listar esquemas de Xcode
      #   run: |
      #     set -e
      #     xcodebuild -list -workspace ios/App/App.xcworkspace

      - name: Configurar Firma en Xcode
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          PROVISIONING_PROFILE_NAME: ${{ secrets.DEV_PROVISIONING_PROFILE_NAME }}
        run: |
          set -e
          cd ios/App

          FILE="App.xcodeproj/project.pbxproj"

          # Asegurar que la firma esté configurada correctamente
          sed -i.bak 's/CODE_SIGN_IDENTITY = "Apple Development";/CODE_SIGN_IDENTITY = "Apple Development";\n        ProvisioningStyle = Manual;\n        DEVELOPMENT_TEAM = '"${APPLE_TEAM_ID}"';\n        PROVISIONING_PROFILE_SPECIFIER = "'"${PROVISIONING_PROFILE_NAME}"'";/g' $FILE

          # Verificar los cambios
          cat $FILE | grep -A 10 "ProvisioningStyle" || true

          rm -f $FILE.bak

      - name: Compilar app iOS
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_BUNDLE_ID: ${{ secrets.APPLE_BUNDLE_ID }}
          PROVISIONING_PROFILE_NAME: ${{ secrets.DEV_PROVISIONING_PROFILE_NAME }}
        run: |
          set -e
          cd ios/App
          xcodebuild clean archive \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $GITHUB_WORKSPACE/build/App.xcarchive \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM=$APPLE_TEAM_ID \
            CODE_SIGN_IDENTITY="Apple Development" \
            PROVISIONING_PROFILE="$PROVISIONING_PROFILE_NAME"

      - name: Exportar IPA
        run: |
          set -e
          xcodebuild -exportArchive \
            -archivePath $GITHUB_WORKSPACE/build/App.xcarchive \
            -exportPath $GITHUB_WORKSPACE/build/App \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -allowProvisioningUpdates \
            -verbose

      - name: Subir IPA como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: iOS-App
          path: build/App/*.ipa

      - name: Limpiar Keychain
        if: always()
        run: |
          set -e
          security delete-keychain build.keychain
